openapi: 3.0.4
info:
  title: OSMS log models
  description: Log models for logging services of OSMS
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Common logging model
      description: Common logging model for all modules
      type: object
      properties:
        messageTime:
          type: string
        logUid:
          type: string
        source:
          type: string
        booking:
          $ref: '#/components/schemas/OsmsLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    OsmsLogModel:
      title: OSMS logging model
      type: object
      properties:
        requestUid:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
        requestBooking:
          $ref: '#/components/schemas/BookingLog'
        requestFilter:
          $ref: '#/components/schemas/BookingFilterLog'
        responseBooking:
          $ref: '#/components/schemas/BookingLog'
        responseBookings:
          type: array
          items:
            $ref: '#/components/schemas/BookingLog'

    ErrorLogModel:
      title: Error logging model
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    BookingLog:
      title: Booking logging model
      type: object
      properties:
        bookingUid:
          type: string
        userUid:
          type: string
        branchUid:
          type: string
        floorUid:
          type: string
        officeUid:
          type: string
        workspaceUid:
          type: string
        startTime:
          type: string
          description: Дата и время начала брони
        endTime:
          type: string
          description: Дата и время окончания брони


    BookingFilterLog:
      title: Filter logging model
      properties:
        bookingUid:
          type: string
        userUid:
          type: string
        branchUid:
          type: string
        floorUid:
          type: string
        officeUid:
          type: string
        workspaceUid:
          type: string
        startTime:
          type: string
          description: Дата и время начала брони
        endTime:
          type: string
          description: Дата и время окончания брони
