version: '3'
services:

  app:
    container_name: osms-app
    image: osms-app-ktor
    depends_on:
      - fluent-bit
      - postgresql
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 2
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/app:/app/etc
    environment:
      - PG_URL=jdbc:postgresql://postgresql:5432/osms
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: app.logs

  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "2020:2020"
    environment:
      - opensearch_host=opensearch
      - opensearch_user=admin
      - opensearch_pass=admin
    volumes:
      - ./volumes/fluent-bit-etc/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./volumes/fluent-bit-etc/parsers.conf:/fluent-bit/etc/parsers.conf

  postgresql:
    container_name: postgresql
    image: postgres:16
    environment:
      POSTGRES_DB: osms
      POSTGRES_USER: osms-app
      POSTGRES_PASSWORD: admin123
      PGDATA: /data/postgres
    volumes:
      - ./volumes/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
